# Generated by Django 5.1 on 2024-08-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time'], 'verbose_name': 'Session'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User'},
        ),
    ]
