# Generated by Django 5.1 on 2024-08-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes', '0003_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='participant',
            field=models.ManyToManyField(related_name='session_participant', to='online_classes.user'),
        ),
    ]
