# Generated by Django 5.1 on 2024-08-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes', '0004_alter_session_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='participant',
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(related_name='sessions', to='online_classes.user'),
        ),
    ]
