# Generated by Django 5.1 on 2024-08-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_classes', '0005_remove_session_participant_session_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
